import type { Metadata } from 'next';
import './globals.css';

// Resolve the canonical site URL for absolute OG/Twitter image + URL tags.
// Falls back gracefully so NO env var is required to build or deploy: prefer an
// explicit NEXT_PUBLIC_SITE_URL, then Vercel's injected VERCEL_URL, then a sane
// default. (metadataBase must be absolute for social previews to resolve.)
const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL ||
  (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'https://foodala.vercel.app');

const title = 'Foodala — Premium food delivery in Davao City';
const description =
  'Browse the best restaurants in Davao City, build your order, and get it delivered. Cash on delivery.';

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: title,
    template: '%s · Foodala',
  },
  description,
  applicationName: 'Foodala',
  keywords: [
    'Foodala',
    'food delivery',
    'Davao City',
    'restaurants',
    'order food',
    'cash on delivery',
  ],
  authors: [{ name: 'Foodala' }],
  // Favicon + app icon sourced from the SAME approved logo asset as mobile
  // (served from /public via a symlink to /assets/branding). One brand mark
  // everywhere — browser tab, bookmarks, and iOS home screen.
  icons: {
    icon: '/foodala-logo-transparent.png',
    shortcut: '/foodala-logo-transparent.png',
    apple: '/foodala-logo-transparent.png',
  },
  openGraph: {
    type: 'website',
    siteName: 'Foodala',
    title,
    description,
    url: siteUrl,
    locale: 'en_PH',
    // The OG image is generated by app/opengraph-image.tsx (no binary asset needed).
  },
  twitter: {
    card: 'summary_large_image',
    title,
    description,
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
